
cradle:

  multi:

    - path: "./test"

      config: { cradle: { stack: {}}}

    - path: "./src"

      config: { cradle: { stack: {}}}

    - path: "./doctest"

      config: { cradle: { stack: {}}}

    - path: "./app2/Main.hs"

      config: { cradle: { stack: {}}}

    - path: "./app1/Main.hs"

      config: { cradle: { stack: {}}}

    - path: "./Setup.hs"

      config: { cradle: { stack: {}}}
